# Generated by Django 5.2.7 on 2025-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bodabodadevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodabodaprofile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
